include( ${CMAKE_CURRENT_LIST_DIR}/cxx_standard.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/pthread.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/sanitizers.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/options.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/cxx_color_diagnostics.cmake )
include( ${CMAKE_CURRENT_LIST_DIR}/update_submodules.cmake )
